/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proyecto.vista;

import com.mycompany.proyecto.controlador.Controlador;
import static com.mycompany.proyecto.controlador.Controlador.menus;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author USUARIO
 */
public class Vista extends javax.swing.JFrame {

    /**
     * Creates new form Vista
     */
    public Vista() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNametitle = new javax.swing.JTextField();
        lblDiff = new javax.swing.JLabel();
        lblInt = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtIntroduction = new javax.swing.JTextArea();
        cbxDiffuculty = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtExplain = new javax.swing.JTextArea();
        btnCancel = new javax.swing.JButton();
        btnCreate = new javax.swing.JButton();
        chkTerms = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitulo.setText("Titulo del curso:");

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 0, 36)); // NOI18N
        jLabel2.setText("CREAR DE CURSO");

        txtNametitle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNametitleActionPerformed(evt);
            }
        });

        lblDiff.setText("Dificultad:");

        lblInt.setText("Introduccion:");

        txtIntroduction.setColumns(20);
        txtIntroduction.setLineWrap(true);
        txtIntroduction.setRows(5);
        txtIntroduction.setWrapStyleWord(true);
        jScrollPane1.setViewportView(txtIntroduction);

        cbxDiffuculty.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5" }));

        jLabel1.setText("Explicacion:");

        txtExplain.setColumns(20);
        txtExplain.setLineWrap(true);
        txtExplain.setRows(5);
        txtExplain.setWrapStyleWord(true);
        jScrollPane2.setViewportView(txtExplain);

        btnCancel.setText("Cancelar");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        btnCreate.setText("Crear");
        btnCreate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCreateMouseClicked(evt);
            }
        });
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });

        chkTerms.setText("Acepto la política de privacidad y los T&C son acuerdos legalmente vinculantes");
        chkTerms.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkTermsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane2))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblInt)
                                    .addComponent(lblDiff)
                                    .addComponent(lblTitulo))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtNametitle)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 481, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbxDiffuculty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chkTerms)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(64, 64, 64)
                                .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(77, 77, 77)
                                .addComponent(btnCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(228, 228, 228)
                        .addComponent(jLabel2)))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel2)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNametitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDiff)
                    .addComponent(cbxDiffuculty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblInt)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(chkTerms)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(77, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNametitleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNametitleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNametitleActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        Controlador.eventobtnCancel();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void chkTermsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkTermsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkTermsActionPerformed

    private void btnCreateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCreateMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCreateMouseClicked

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
        if(txtNametitle.getText().isEmpty() || txtIntroduction.getText().isEmpty() || txtExplain.getText().isEmpty()){
            JOptionPane.showMessageDialog(rootPane, "Tiene que llenar todos los campos");
        }else{
        if(chkTerms.isSelected()){
        Cursos a = new Cursos();
        a.setVisible(true);
        a.setLocationRelativeTo(null);
        String info=txtNametitle.getText();
        Cursos.txtTitle2.setText(info);
        String info2=txtIntroduction.getText();
        Cursos.txtInt2.setText(info2);
        String info3=txtExplain.getText();
        Cursos.txtExp2.setText(info3);
        Cursos.txtDiff2.setText(cbxDiffuculty.getSelectedItem().toString());
        Controlador.eventobtnCreate();
        Cursos.txtTitle2.setEditable(false);
        Cursos.txtInt2.setEditable(false);
        Cursos.txtExp2.setEditable(false);
        Cursos.txtDiff2.setEditable(false);
        }else{
            JOptionPane.showMessageDialog(rootPane, "Tiene que aceptar los Terminos y Condiciones");
        }
        }
        
    }//GEN-LAST:event_btnCreateActionPerformed

    public JButton getBtnCancel() {
        return btnCancel;
    }

    public void setBtnCancel(JButton btnCancel) {
        this.btnCancel = btnCancel;
    }

    public JButton getBtnCreate() {
        return btnCreate;
    }

    public void setBtnCreate(JButton btnCreate) {
        this.btnCreate = btnCreate;
    }

    public JComboBox<String> getCbxDiffuculty() {
        return cbxDiffuculty;
    }

    public void setCbxDiffuculty(JComboBox<String> cbxDiffuculty) {
        this.cbxDiffuculty = cbxDiffuculty;
    }

    public JCheckBox getChcTerms() {
        return chkTerms;
    }

    public void setChcTerms(JCheckBox chcTerms) {
        this.chkTerms = chcTerms;
    }

    public JLabel getjLabel1() {
        return jLabel1;
    }

    public void setjLabel1(JLabel jLabel1) {
        this.jLabel1 = jLabel1;
    }

    public JLabel getjLabel2() {
        return jLabel2;
    }

    public void setjLabel2(JLabel jLabel2) {
        this.jLabel2 = jLabel2;
    }

    public JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    public void setjScrollPane1(JScrollPane jScrollPane1) {
        this.jScrollPane1 = jScrollPane1;
    }

    public JScrollPane getjScrollPane2() {
        return jScrollPane2;
    }

    public void setjScrollPane2(JScrollPane jScrollPane2) {
        this.jScrollPane2 = jScrollPane2;
    }

    public JLabel getLblDiff() {
        return lblDiff;
    }

    public void setLblDiff(JLabel lblDiff) {
        this.lblDiff = lblDiff;
    }

    public JLabel getLblInt() {
        return lblInt;
    }

    public void setLblInt(JLabel lblInt) {
        this.lblInt = lblInt;
    }

    public JLabel getLblTitulo() {
        return lblTitulo;
    }

    public void setLblTitulo(JLabel lblTitulo) {
        this.lblTitulo = lblTitulo;
    }

    public JTextArea getTxtExplain() {
        return txtExplain;
    }

    public void setTxtExplain(JTextArea txtExplain) {
        this.txtExplain = txtExplain;
    }

    public JTextArea getTxtIntroduction() {
        return txtIntroduction;
    }

    public void setTxtIntroduction(JTextArea txtIntroduction) {
        this.txtIntroduction = txtIntroduction;
    }

    public JTextField getTxtNametitle() {
        return txtNametitle;
    }

    public void setTxtNametitle(JTextField txtNametitle) {
        this.txtNametitle = txtNametitle;
    }
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    public javax.swing.JButton btnCreate;
    public static javax.swing.JComboBox<String> cbxDiffuculty;
    public static javax.swing.JCheckBox chkTerms;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblDiff;
    private javax.swing.JLabel lblInt;
    private javax.swing.JLabel lblTitulo;
    public static javax.swing.JTextArea txtExplain;
    public static javax.swing.JTextArea txtIntroduction;
    public static javax.swing.JTextField txtNametitle;
    // End of variables declaration//GEN-END:variables
}
